contents:
- mLevel: OP_Dungeon
  mShadowMap:
    mAabb:
      mMax:
        mX: 18.0
        mY: 15.0
        mZ: 15.0
      mMin:
        mX: 18.0
        mY: 15.0
        mZ: 30.0
    mDintance:
      mBegin: 1000.0
      mEnd: 1500.0
    mKey: Medium
- mLevel: EV_OPField
  mShadowMap:
    mAabb:
      mMax:
        mX: 60.0
        mY: 60.0
        mZ: 15.0
      mMin:
        mX: 250.0
        mY: 20.0
        mZ: 250.0
    mDintance:
      mBegin: 80.0
      mEnd: 250.0
    mKey: Demo_L
- mLevel: S_Dungeon006
  mShadowMap:
    mAabb:
      mMax:
        mX: 18.0
        mY: 15.0
        mZ: 15.0
      mMin:
        mX: 18.0
        mY: 15.0
        mZ: 30.0
    mDintance:
      mBegin: 1000.0
      mEnd: 1500.0
    mKey: Medium
- mLevel: FieldBoundary004_002
  mShadowMap:
    mAabb:
      mMax:
        mX: 15.0
        mY: 10.0
        mZ: 10.0
      mMin:
        mX: 15.0
        mY: 40.0
        mZ: 35.0
    mDintance:
      mBegin: 35.0
      mEnd: 70.0
    mKey: BossVolvagia
- mLevel: EV_WorldRepairForest
  mShadowMap:
    mAabb:
      mMax:
        mX: 15.0
        mY: 15.0
        mZ: 10.0
      mMin:
        mX: 15.0
        mY: 60.0
        mZ: 60.0
    mDintance:
      mBegin: 1000.0
      mEnd: 1500.0
    mKey: WorldRepair
- mLevel: EV_WorldRepairRiver
  mShadowMap:
    mAabb:
      mMax:
        mX: 15.0
        mY: 15.0
        mZ: 10.0
      mMin:
        mX: 15.0
        mY: 60.0
        mZ: 60.0
    mDintance:
      mBegin: 1000.0
      mEnd: 1500.0
    mKey: WorldRepair
- mLevel: Ev_WorldRepairDesert
  mShadowMap:
    mAabb:
      mMax:
        mX: 15.0
        mY: 15.0
        mZ: 10.0
      mMin:
        mX: 15.0
        mY: 60.0
        mZ: 60.0
    mDintance:
      mBegin: 1000.0
      mEnd: 1500.0
    mKey: WorldRepair
- mLevel: EV_WorldRepairCastle
  mShadowMap:
    mAabb:
      mMax:
        mX: 15.0
        mY: 15.0
        mZ: 10.0
      mMin:
        mX: 15.0
        mY: 60.0
        mZ: 60.0
    mDintance:
      mBegin: 1000.0
      mEnd: 1500.0
    mKey: WorldRepair
- mLevel: EV_WorldRepairVolcano
  mShadowMap:
    mAabb:
      mMax:
        mX: 15.0
        mY: 15.0
        mZ: 10.0
      mMin:
        mX: 15.0
        mY: 60.0
        mZ: 60.0
    mDintance:
      mBegin: 1000.0
      mEnd: 1500.0
    mKey: WorldRepair
- mLevel: EV_WorldRepairJungle
  mShadowMap:
    mAabb:
      mMax:
        mX: 15.0
        mY: 15.0
        mZ: 10.0
      mMin:
        mX: 15.0
        mY: 60.0
        mZ: 60.0
    mDintance:
      mBegin: 1000.0
      mEnd: 1500.0
    mKey: WorldRepair
- mLevel: EV_WorldRepairHebraMountain
  mShadowMap:
    mAabb:
      mMax:
        mX: 15.0
        mY: 15.0
        mZ: 10.0
      mMin:
        mX: 15.0
        mY: 60.0
        mZ: 60.0
    mDintance:
      mBegin: 1000.0
      mEnd: 1500.0
    mKey: WorldRepair
- mLevel: Field
  mShadowMap:
    mAabb:
      mMax:
        mX: 15.0
        mY: 15.0
        mZ: 10.0
      mMin:
        mX: 15.0
        mY: 20.0
        mZ: 25.0
    mDintance:
      mBegin: 50.0
      mEnd: 70.0
    mKey: Field
fields:
- fields: []
  flags: 4
  name: mLevel
  type: 4
  type_name: string
- fields:
  - fields: []
    flags: 4
    name: mKey
    type: 4
    type_name: string
  - fields:
    - fields:
      - fields: []
        flags: 0
        name: mX
        type: 3
        type_name: float
      - fields: []
        flags: 0
        name: mY
        type: 3
        type_name: float
      - fields: []
        flags: 0
        name: mZ
        type: 3
        type_name: float
      flags: 0
      name: mMin
      type: 0
      type_name: __inline_struct_ShadowMapSettings_mAabb.mMin
    - fields:
      - fields: []
        flags: 0
        name: mX
        type: 3
        type_name: float
      - fields: []
        flags: 0
        name: mY
        type: 3
        type_name: float
      - fields: []
        flags: 0
        name: mZ
        type: 3
        type_name: float
      flags: 0
      name: mMax
      type: 0
      type_name: __inline_struct_ShadowMapSettings_mAabb.mMax
    flags: 0
    name: mAabb
    type: 0
    type_name: __inline_struct_ShadowMapSettings_mAabb
  - fields:
    - fields: []
      flags: 0
      name: mBegin
      type: 3
      type_name: float
    - fields: []
      flags: 0
      name: mEnd
      type: 3
      type_name: float
    flags: 0
    name: mDintance
    type: 0
    type_name: __inline_struct_ShadowMapSettings_mDintance
  flags: 0
  name: mShadowMap
  type: 0
  type_name: ShadowMapSettings
