contents:
- mAabb:
    mMax:
      mX: 15.0
      mY: 15.0
      mZ: 10.0
    mMin:
      mX: 15.0
      mY: 15.0
      mZ: 20.0
  mDintance:
    mBegin: 1000.0
    mEnd: 1500.0
  mKey: Default
- mAabb:
    mMax:
      mX: 18.0
      mY: 15.0
      mZ: 15.0
    mMin:
      mX: 18.0
      mY: 15.0
      mZ: 30.0
  mDintance:
    mBegin: 1000.0
    mEnd: 1500.0
  mKey: Medium
- mAabb:
    mMax:
      mX: 20.0
      mY: 30.0
      mZ: 20.0
    mMin:
      mX: 20.0
      mY: 15.0
      mZ: 20.0
  mDintance:
    mBegin: 50.0
    mEnd: 75.0
  mKey: Demo_M
- mAabb:
    mMax:
      mX: 60.0
      mY: 60.0
      mZ: 15.0
    mMin:
      mX: 250.0
      mY: 20.0
      mZ: 250.0
  mDintance:
    mBegin: 80.0
    mEnd: 250.0
  mKey: Demo_L
- mAabb:
    mMax:
      mX: 15.0
      mY: 15.0
      mZ: 10.0
    mMin:
      mX: 15.0
      mY: 15.0
      mZ: 40.0
  mDintance:
    mBegin: 60.0
    mEnd: 100.0
  mKey: DemoStageCamera
- mAabb:
    mMax:
      mX: 15.0
      mY: 15.0
      mZ: 10.0
    mMin:
      mX: 15.0
      mY: 15.0
      mZ: 180.0
  mDintance:
    mBegin: 1000.0
    mEnd: 1500.0
  mKey: FieldBoundary1
- mAabb:
    mMax:
      mX: 15.0
      mY: 10.0
      mZ: 20.0
    mMin:
      mX: 15.0
      mY: 15.0
      mZ: 15.0
  mDintance:
    mBegin: 1000.0
    mEnd: 1500.0
  mKey: FieldBoundary2
- mAabb:
    mMax:
      mX: 15.0
      mY: 10.0
      mZ: 10.0
    mMin:
      mX: 15.0
      mY: 40.0
      mZ: 35.0
  mDintance:
    mBegin: 35.0
    mEnd: 70.0
  mKey: BossVolvagia
- mAabb:
    mMax:
      mX: 15.0
      mY: 45.0
      mZ: 10.0
    mMin:
      mX: 15.0
      mY: 15.0
      mZ: 20.0
  mDintance:
    mBegin: 1000.0
    mEnd: 1500.0
  mKey: HighCeiling
- mAabb:
    mMax:
      mX: 15.0
      mY: 15.0
      mZ: 10.0
    mMin:
      mX: 15.0
      mY: 60.0
      mZ: 60.0
  mDintance:
    mBegin: 1000.0
    mEnd: 1500.0
  mKey: WorldRepair
- mAabb:
    mMax:
      mX: 15.0
      mY: 15.0
      mZ: 10.0
    mMin:
      mX: 15.0
      mY: 20.0
      mZ: 25.0
  mDintance:
    mBegin: 50.0
    mEnd: 70.0
  mKey: Field
fields:
- fields: []
  flags: 4
  name: mKey
  type: 4
  type_name: string
- fields:
  - fields:
    - fields: []
      flags: 0
      name: mX
      type: 3
      type_name: float
    - fields: []
      flags: 0
      name: mY
      type: 3
      type_name: float
    - fields: []
      flags: 0
      name: mZ
      type: 3
      type_name: float
    flags: 0
    name: mMin
    type: 0
    type_name: __inline_struct_ShadowMapSettings_mAabb.mMin
  - fields:
    - fields: []
      flags: 0
      name: mX
      type: 3
      type_name: float
    - fields: []
      flags: 0
      name: mY
      type: 3
      type_name: float
    - fields: []
      flags: 0
      name: mZ
      type: 3
      type_name: float
    flags: 0
    name: mMax
    type: 0
    type_name: __inline_struct_ShadowMapSettings_mAabb.mMax
  flags: 0
  name: mAabb
  type: 0
  type_name: __inline_struct_ShadowMapSettings_mAabb
- fields:
  - fields: []
    flags: 0
    name: mBegin
    type: 3
    type_name: float
  - fields: []
    flags: 0
    name: mEnd
    type: 3
    type_name: float
  flags: 0
  name: mDintance
  type: 0
  type_name: __inline_struct_ShadowMapSettings_mDintance
