contents:
- mRegion: BossDeguZol
  mShadowMap:
    mAabb:
      mMax:
        mX: 15.0
        mY: 45.0
        mZ: 10.0
      mMin:
        mX: 15.0
        mY: 15.0
        mZ: 20.0
    mDintance:
      mBegin: 1000.0
      mEnd: 1500.0
    mKey: HighCeiling
- mRegion: BossMogriffon
  mShadowMap:
    mAabb:
      mMax:
        mX: 15.0
        mY: 45.0
        mZ: 10.0
      mMin:
        mX: 15.0
        mY: 15.0
        mZ: 20.0
    mDintance:
      mBegin: 1000.0
      mEnd: 1500.0
    mKey: HighCeiling
fields:
- fields: []
  flags: 4
  name: mRegion
  type: 4
  type_name: string
- fields:
  - fields: []
    flags: 4
    name: mKey
    type: 4
    type_name: string
  - fields:
    - fields:
      - fields: []
        flags: 0
        name: mX
        type: 3
        type_name: float
      - fields: []
        flags: 0
        name: mY
        type: 3
        type_name: float
      - fields: []
        flags: 0
        name: mZ
        type: 3
        type_name: float
      flags: 0
      name: mMin
      type: 0
      type_name: __inline_struct_ShadowMapSettings_mAabb.mMin
    - fields:
      - fields: []
        flags: 0
        name: mX
        type: 3
        type_name: float
      - fields: []
        flags: 0
        name: mY
        type: 3
        type_name: float
      - fields: []
        flags: 0
        name: mZ
        type: 3
        type_name: float
      flags: 0
      name: mMax
      type: 0
      type_name: __inline_struct_ShadowMapSettings_mAabb.mMax
    flags: 0
    name: mAabb
    type: 0
    type_name: __inline_struct_ShadowMapSettings_mAabb
  - fields:
    - fields: []
      flags: 0
      name: mBegin
      type: 3
      type_name: float
    - fields: []
      flags: 0
      name: mEnd
      type: 3
      type_name: float
    flags: 0
    name: mDintance
    type: 0
    type_name: __inline_struct_ShadowMapSettings_mDintance
  flags: 0
  name: mShadowMap
  type: 0
  type_name: ShadowMapSettings
